//Authentication -> Authentication means verifying the user's identity. In this case, the user is the one who is trying to access the application.
// The user can be authenticated using a username and password. The user can also be authenticated using a token. The token is a unique string that is generated by the server and sent to the user. 
//The user can then use this token to access the application. The token is usually valid for a certain period of time. If the token expires, the user will need to log in again to get a new token. 
//The token is usually stored in a cookie or a session variable. The token is sent to the server with each request. 
//The server then verifies the token and allows the user to access the application. The token is usually encrypted to prevent it from being tampered with. 
//The token is usually generated using a cryptographic algorithm. The token is usually stored in a database

// Authorization -> Authorization means determining what the user is allowed to do. In this case, the user is the one who is trying to access the application.

// Token based authentication -> Token-based authentication is a method of authenticating users using a token. The token is a unique string that is generated by the server and sent to the user.


// Customer
//"email": "john.doe123@example.com",
//    "password": "password123"

//    "email": "shivani123@example.com",
 //   "password": "password12345